### ISSUE TITLE
请问有没有实验效果对比？

### ISSUE THREAD

**Issue by brotherb** [yao8839836/fast_text_gcn#4]
RT

**Comment by yao8839836** [comment]
@brotherb 只比了20ng, Accuracy最高刷到0.84左右，比原始Text GCN低一些

**Comment by brotherb** [comment]
> @brotherb 只比了20ng, Accuracy最高刷到0.84左右，比原始Text GCN低一些

好的，谢谢

**Comment by guotong1988** [comment]
THX, same question.
