### ISSUE TITLE
请问，如果我有预先训练的词向量，需要修改fast_text_gcn的那些代码？

### ISSUE THREAD

**Issue by iimlearning** [yao8839836/fast_text_gcn#5]
我有预训练的词向量，我想把它们作为图卷积神经网络的初值，我该如何修改代码，该修改哪些部分呢？
谢谢
祝好

**Comment by yao8839836** [comment]
@iimlearning 

您好，需要将utils.py的221行    features = sp.identity(features.shape[0])注释掉，allx, x, tx等文件生成时写入词向量。Text GGN的build_graph.py中有写入词向量代码，只是我发现加词向量效果不好，就把存词向量的字典设置为空, 也就是{}。

**Comment by iimlearning** [comment]
> @iimlearning
> 
> 您好，需要将utils.py的221行 features = sp.identity(features.shape[0])注释掉，allx, x, tx等文件生成时写入词向量。Text GGN的build_graph.py中有写入词向量代码，只是我发现加词向量效果不好，就把存词向量的字典设置为空, 也就是{}。

谢谢你。

**Comment by iimlearning** [comment]
@yao8839836 

对了，您是否考虑过在GCN中加入位置信息呢？因为对于我的数据集而言，位置信息极其的重要甚至决定了最终的结果。如果您有考虑过，或读过类似的论文，可以分享一下吗？谢谢您。

**Comment by yao8839836** [comment]
@iimlearning 

您好，可参考
http://proceedings.mlr.press/v97/you19b/you19b.pdf
https://www.aclweb.org/anthology/D19-1345.pdf
